package components;

public enum Commands {
    VALIDATE_LOGIN,
    USER_REGISTER,
    ADD_BOOK,
    GET_USER,
    LOAD_SECURITY_QUESTIONS,
    CUSTOMER_REGISTER,
    PUBLISHER_REGISTER,
    UPDATE_PASSWORD,
    GET_ALL_AUTHOR_CATEGORY,
    GET_BOOKS_LIST,
    GET_ALL_TITLE_PUBLISHER, GET_BOOKS_LIST_2, LOAD_PUBLISHERS, DELETE_BOOK
}
